"use client"

import { useMemo } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Download } from "lucide-react"
import type { Debt, PayoffStrategy, PayoffResult } from "@/components/goals/types"
import {
  formatCurrency,
  formatPrecise,
  formatCompact,
  formatMonthsShort,
} from "@/components/goals/types"

interface PayoffResultsProps {
  debts: Debt[]
  strategy: PayoffStrategy
  extraPayment: number
  result: PayoffResult
  allResults: Record<string, PayoffResult>
}

function generatePayoffReportHTML(
  debts: Debt[],
  results: Record<string, PayoffResult>,
  strategy: string,
  extraPayment: number
): string {
  const totalDebt = debts.reduce((sum, d) => sum + d.balance, 0)
  const result = results[strategy]

  const debtRows = debts
    .map(
      (d) => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #1a2332;">${d.name}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #1a2332;">${d.type}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #1a2332;text-align:right;color:#ef4444;">$${d.balance.toLocaleString("en-US", { minimumFractionDigits: 2 })}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #1a2332;text-align:right;color:#f97316;">${d.apr}%</td>
      <td style="padding:10px 12px;border-bottom:1px solid #1a2332;text-align:right;">$${d.monthlyPayment.toFixed(2)}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #1a2332;text-align:right;color:#f97316;">$${((d.balance * d.apr / 100) / 12).toFixed(2)}</td>
    </tr>`
    )
    .join("")

  const strategyRows = (["snowball", "avalanche"] as const)
    .map((s) => {
      const r = results[s]
      const saving = r.totalInterestPaid - results.snowball.totalInterestPaid
      const isActive = s === strategy
      return `
      <tr style="${isActive ? "background:#0a2a1a;" : ""}">
        <td style="padding:10px 12px;border-bottom:1px solid #1a2332;font-weight:${isActive ? "bold" : "normal"};color:${isActive ? "#22c55e" : "#e5e7eb"};">
          ${s.charAt(0).toUpperCase() + s.slice(1)}
        </td>
        <td style="padding:10px 12px;border-bottom:1px solid #1a2332;">$${extraPayment.toFixed(2)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #1a2332;">${formatMonthsShort(r.totalMonths)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #1a2332;color:#f97316;">$${r.totalInterestPaid.toFixed(2)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #1a2332;">$${r.totalCost.toFixed(2)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #1a2332;color:${saving < 0 ? "#22c55e" : saving > 0 ? "#ef4444" : "#9ca3af"};">
          ${saving < 0 ? "save $" + Math.abs(saving).toFixed(2) : saving > 0 ? "+$" + saving.toFixed(2) : "\u2014"}
        </td>
      </tr>`
    })
    .join("")

  return `<!DOCTYPE html>
<html><head><title>WealthClaude \u2014 Debt Payoff Report</title></head>
<body style="font-family:'Segoe UI',system-ui,sans-serif;max-width:860px;margin:0 auto;padding:40px;color:#e5e7eb;background:#0a0f1a;">
  <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px;">
    <div style="width:36px;height:36px;background:linear-gradient(135deg,#22c55e,#16a34a);border-radius:8px;display:flex;align-items:center;justify-content:center;">
      <span style="color:white;font-weight:bold;font-size:18px;">W</span>
    </div>
    <h1 style="color:#fff;margin:0;font-size:28px;">Debt Payoff Report</h1>
  </div>
  <p style="color:#6b7280;margin:0 0 24px 48px;font-size:13px;">Generated by WealthClaude on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
  <hr style="border:none;border-top:1px solid #1a2332;margin:0 0 28px;">
  <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:16px;margin-bottom:28px;">
    <div style="background:#111827;border:1px solid #1a2332;border-radius:10px;padding:16px;"><p style="color:#6b7280;font-size:12px;margin:0 0 4px;text-transform:uppercase;">Total Debt</p><p style="color:#ef4444;font-size:24px;font-weight:bold;margin:0;">$${totalDebt.toLocaleString("en-US", { minimumFractionDigits: 2 })}</p></div>
    <div style="background:#111827;border:1px solid #1a2332;border-radius:10px;padding:16px;"><p style="color:#6b7280;font-size:12px;margin:0 0 4px;text-transform:uppercase;">Payoff Date</p><p style="color:#22c55e;font-size:24px;font-weight:bold;margin:0;">${result.debtFreeDate}</p></div>
    <div style="background:#111827;border:1px solid #1a2332;border-radius:10px;padding:16px;"><p style="color:#6b7280;font-size:12px;margin:0 0 4px;text-transform:uppercase;">Total Interest</p><p style="color:#f97316;font-size:24px;font-weight:bold;margin:0;">$${result.totalInterestPaid.toFixed(2)}</p></div>
    <div style="background:#111827;border:1px solid #1a2332;border-radius:10px;padding:16px;"><p style="color:#6b7280;font-size:12px;margin:0 0 4px;text-transform:uppercase;">Monthly Budget</p><p style="color:#e5e7eb;font-size:24px;font-weight:bold;margin:0;">$${result.monthlyBudget.toFixed(2)}</p></div>
  </div>
  <h2 style="color:#fff;font-size:16px;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px;">Debt Details</h2>
  <table style="width:100%;border-collapse:collapse;margin-bottom:28px;background:#111827;border-radius:10px;overflow:hidden;">
    <thead><tr style="background:#0d1524;"><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Name</th><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Type</th><th style="padding:10px 12px;text-align:right;color:#6b7280;font-size:11px;text-transform:uppercase;">Balance</th><th style="padding:10px 12px;text-align:right;color:#6b7280;font-size:11px;text-transform:uppercase;">APR</th><th style="padding:10px 12px;text-align:right;color:#6b7280;font-size:11px;text-transform:uppercase;">Min Payment</th><th style="padding:10px 12px;text-align:right;color:#6b7280;font-size:11px;text-transform:uppercase;">Interest/Mo</th></tr></thead>
    <tbody>${debtRows}</tbody>
  </table>
  <h2 style="color:#fff;font-size:16px;text-transform:uppercase;letter-spacing:1px;margin-bottom:12px;">Strategy Comparison</h2>
  <table style="width:100%;border-collapse:collapse;margin-bottom:28px;background:#111827;border-radius:10px;overflow:hidden;">
    <thead><tr style="background:#0d1524;"><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Strategy</th><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Extra/Mo</th><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Payoff Time</th><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Total Interest</th><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">Total Cost</th><th style="padding:10px 12px;text-align:left;color:#6b7280;font-size:11px;text-transform:uppercase;">vs Snowball</th></tr></thead>
    <tbody>${strategyRows}</tbody>
  </table>
  <div style="background:linear-gradient(135deg,#0a2a1a,#0d1524);border:2px solid #22c55e40;border-radius:12px;padding:24px;margin-bottom:28px;">
    <p style="color:#22c55e;font-size:12px;text-transform:uppercase;letter-spacing:1px;margin:0 0 8px;">\u2726 Your Action Plan</p>
    <p style="color:#fff;font-size:20px;font-weight:bold;margin:0;">Pay $${extraPayment.toFixed(2)} extra/month using ${strategy.charAt(0).toUpperCase() + strategy.slice(1)} \u2192 debt free in ${formatMonthsShort(result.totalMonths)}</p>
  </div>
  <hr style="border:none;border-top:1px solid #1a2332;margin:28px 0;">
  <p style="color:#4b5563;font-size:11px;text-align:center;">This report is for informational purposes only.<br/>Generated by WealthClaude \u00b7 wealthclaude.com</p>
  <p style="color:#4b5563;font-size:10px;text-align:center;margin-top:4px;">Includes card summary \u00b7 strategy comparison \u00b7 goal scenarios \u00b7 balance chart</p>
</body></html>`
}

export function PayoffResults({
  debts,
  strategy,
  extraPayment,
  result,
  allResults,
}: PayoffResultsProps) {
  const totalDebt = debts.reduce((sum, d) => sum + d.balance, 0)
  const savingsVsSnowball =
    allResults.snowball.totalInterestPaid - result.totalInterestPaid
  const weightedAvgAPR =
    totalDebt > 0
      ? debts.reduce((sum, d) => sum + d.balance * d.apr, 0) / totalDebt
      : 0

  // Balance over time gradient segments
  const balanceSegments = useMemo(() => {
    if (result.totalMonths === 0) return []
    const totalMo = result.totalMonths
    const segCount = Math.min(totalMo, 20)
    const step = Math.max(1, Math.floor(totalMo / segCount))
    const segs: { month: number; balance: number; ratio: number }[] = []

    for (let i = 0; i < totalMo; i += step) {
      const e = result.monthlySchedule[i]
      if (e) {
        segs.push({
          month: e.month,
          balance: e.totalBalance,
          ratio: totalDebt > 0 ? e.totalBalance / totalDebt : 0,
        })
      }
    }
    if (
      segs.length > 0 &&
      segs[segs.length - 1].month !== totalMo
    ) {
      segs.push({ month: totalMo, balance: 0, ratio: 0 })
    }
    return segs
  }, [result, totalDebt])

  const handleDownload = () => {
    const html = generatePayoffReportHTML(
      debts,
      allResults,
      strategy,
      extraPayment
    )
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `WealthClaude-Debt-Report-${new Date().toISOString().split("T")[0]}.html`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <>
      {/* Action Plan Banner */}
      <Card className="border-2 border-green-500/30 bg-gradient-to-r from-green-500/5 to-card">
        <CardContent className="pt-6 pb-6">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-green-500 mb-2">
            ✦ Your Action Plan
          </p>
          <p className="text-xl lg:text-2xl font-bold text-foreground">
            Pay {formatPrecise(extraPayment)} extra/month using{" "}
            <span className="text-green-500">
              {strategy.charAt(0).toUpperCase() + strategy.slice(1)}
            </span>{" "}
            → debt free in{" "}
            <span className="text-green-500">
              {formatMonthsShort(result.totalMonths)}
            </span>
            {savingsVsSnowball > 0 && (
              <>
                , saving{" "}
                <span className="text-green-500">
                  {formatPrecise(savingsVsSnowball)}
                </span>{" "}
                vs snowball
              </>
            )}
          </p>
          <p className="text-xs text-muted-foreground mt-2">
            {weightedAvgAPR > 20
              ? "🔥 Mixed / Unknown pattern detected — "
              : "📊 Mixed / Unknown pattern detected — "}
            {strategy === "avalanche"
              ? "Avalanche targets highest APR first — saves the most money."
              : "Snowball targets smallest balance first — builds momentum with quick wins."}
          </p>
        </CardContent>
      </Card>

      {/* Result Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
              Payoff Date
            </p>
            <p className="text-2xl font-bold text-green-500">
              {result.debtFreeDate}
            </p>
          </CardContent>
        </Card>
        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
              Total Interest
            </p>
            <p className="text-2xl font-bold text-orange-500">
              {formatPrecise(result.totalInterestPaid)}
            </p>
          </CardContent>
        </Card>
        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
              Total Cost
            </p>
            <p className="text-2xl font-bold text-foreground">
              {formatPrecise(result.totalCost)}
            </p>
          </CardContent>
        </Card>
        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">
              Monthly Budget
            </p>
            <p className="text-2xl font-bold text-foreground">
              {formatPrecise(result.monthlyBudget)}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Balance Over Time Gradient Bar */}
      {balanceSegments.length > 0 && (
        <Card className="border-border bg-card">
          <CardContent className="pt-6">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground mb-4">
              Balance Over Time
            </p>
            <div className="flex h-10 rounded-lg overflow-hidden">
              {balanceSegments.map((seg, i) => {
                const ratio = seg.ratio
                // Red (high debt) → Orange → Yellow → Green (debt free)
                const r = Math.round(239 * ratio + 34 * (1 - ratio))
                const g = Math.round(68 * ratio + 197 * (1 - ratio))
                const b = Math.round(68 * ratio + 94 * (1 - ratio))
                return (
                  <div
                    key={i}
                    className="flex-1 transition-all"
                    style={{ backgroundColor: `rgb(${r},${g},${b})` }}
                    title={`Month ${seg.month}: ${formatCurrency(seg.balance)}`}
                  />
                )
              })}
            </div>
            <div className="flex justify-between mt-2 text-xs text-muted-foreground">
              <span>Today — {formatCompact(totalDebt)}</span>
              <span>Debt Free 🎉</span>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Download PDF Button */}
      <button
        onClick={handleDownload}
        className="w-full rounded-lg border-2 border-border bg-card py-4 flex items-center justify-center gap-3 hover:bg-secondary/50 transition-colors"
      >
        <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-green-500 to-green-600 flex items-center justify-center">
          <Download className="h-4 w-4 text-black" />
        </div>
        <div className="text-left">
          <p className="text-sm font-bold text-foreground">
            Download Payoff Plan PDF
          </p>
          <p className="text-xs text-muted-foreground">
            — WealthClaude branded
          </p>
        </div>
      </button>
      <p className="text-[10px] text-center text-muted-foreground -mt-3">
        Includes card summary · strategy comparison · goal scenarios · balance chart
      </p>
    </>
  )
}
