export const holdings: Holding[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    shares: 50,
    avgCost: 150.00,
    currentPrice: 178.50,
    marketValue: 8925.00,
    costBasis: 7500.00,
    allocation: 14.82,
    dailyChange: 125.00,
    dailyChangePercent: 1.42,
    totalGain: 1425.00,
    totalGainPercent: 19.00,
    sector: 'Technology',
    industry: 'Consumer Electronics',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/apple.com'
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    shares: 30,
    avgCost: 340.00,
    currentPrice: 378.20,
    marketValue: 11346.00,
    costBasis: 10200.00,
    allocation: 18.84,
    dailyChange: 180.00,
    dailyChangePercent: 1.61,
    totalGain: 1146.00,
    totalGainPercent: 11.24,
    sector: 'Technology',
    industry: 'Software',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/microsoft.com'
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    shares: 40,
    avgCost: 120.00,
    currentPrice: 141.80,
    marketValue: 5672.00,
    costBasis: 4800.00,
    allocation: 9.42,
    dailyChange: 85.00,
    dailyChangePercent: 1.52,
    totalGain: 872.00,
    totalGainPercent: 18.17,
    sector: 'Technology',
    industry: 'Internet Services',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/google.com'
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    shares: 100,
    avgCost: 120.00,
    currentPrice: 170.63,
    marketValue: 17062.50,
    costBasis: 12000.00,
    allocation: 28.33,
    dailyChange: 340.00,
    dailyChangePercent: 2.03,
    totalGain: 5062.50,
    totalGainPercent: 42.19,
    sector: 'Technology',
    industry: 'Semiconductors',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/nvidia.com'
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    shares: 35,
    avgCost: 140.00,
    currentPrice: 178.90,
    marketValue: 6261.50,
    costBasis: 4900.00,
    allocation: 10.40,
    dailyChange: 94.00,
    dailyChangePercent: 1.52,
    totalGain: 1361.50,
    totalGainPercent: 27.79,
    sector: 'Consumer Cyclical',
    industry: 'E-Commerce',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/amazon.com'
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    shares: 20,
    avgCost: 200.00,
    currentPrice: 248.60,
    marketValue: 4972.00,
    costBasis: 4000.00,
    allocation: 8.26,
    dailyChange: 74.00,
    dailyChangePercent: 1.51,
    totalGain: 972.00,
    totalGainPercent: 24.30,
    sector: 'Consumer Cyclical',
    industry: 'Auto Manufacturers',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/tesla.com'
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    shares: 25,
    avgCost: 150.00,
    currentPrice: 195.20,
    marketValue: 4880.00,
    costBasis: 3750.00,
    allocation: 8.10,
    dailyChange: 73.00,
    dailyChangePercent: 1.52,
    totalGain: 1130.00,
    totalGainPercent: 30.13,
    sector: 'Financial',
    industry: 'Banking',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/jpmorganchase.com'
  },
  {
    symbol: 'V',
    name: 'Visa Inc.',
    shares: 10,
    avgCost: 240.00,
    currentPrice: 275.30,
    marketValue: 2753.00,
    costBasis: 2400.00,
    allocation: 4.57,
    dailyChange: 41.00,
    dailyChangePercent: 1.51,
    totalGain: 353.00,
    totalGainPercent: 14.71,
    sector: 'Financial',
    industry: 'Payment Services',
    country: 'USA',
    assetType: 'Stock',
    logo: 'https://logo.clearbit.com/visa.com'
  },
  {
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    shares: 20,
    avgCost: 200.00,
    currentPrice: 211.38,
    marketValue: 4227.50,
    costBasis: 4000.00,
    allocation: 7.02,
    dailyChange: 63.00,
    dailyChangePercent: 1.51,
    totalGain: 227.50,
    totalGainPercent: 5.69,
    sector: 'Diversified',
    industry: 'Index Fund',
    country: 'USA',
    assetType: 'ETF',
    logo: 'https://logo.clearbit.com/vanguard.com'
  }
]
